// dotenv
require("dotenv").config({ quiet: true });

// Express
const express = require("express");
const app = express();
app.set("trust proxy", 1);

// routes
const bookShelfRouter = require("./routes/bookshelf");
const reviewRouter = require("./routes/review");
const userRouter = require("./routes/auth");

//middleware
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// Others
const createError = require("http-errors");
const cookieParser = require("cookie-parser");

// CORS
const cors = require("cors");

const allowedOrigins = [
  "http://localhost:5173",
  "https://book-shelf-two-peach.vercel.app",
  "https://book-shelf-git-main-ninjaz9s-projects.vercel.app",
];

// 2. Create a smart CORS function
const corsOptions = {
  origin: function (origin, callback) {
    // Allow requests with no origin (like Postman or mobile apps)
    if (!origin) return callback(null, true);

    // Check if the URL is in our exact list above
    if (allowedOrigins.includes(origin)) {
      return callback(null, true);
    }
    // MAGIC TRICK: Automatically allow any dynamic Vercel deployment URL generated by your account
    else if (origin.endsWith("-ninjaz9s-projects.vercel.app")) {
      return callback(null, true);
    }
    // Block everything else
    else {
      return callback(new Error("Blocked by CORS policy"), false);
    }
  },
  methods: "GET,PUT,PATCH,POST,DELETE",
  credentials: true,
  optionsSuccessStatus: 200,
};

app.use(cors(corsOptions));
app.use(cookieParser());

// Mongoose
const mongoose = require("mongoose");

const main = async () => {
  try {
    await mongoose.connect(process.env.DATABASE_URL);
    console.log("DataBase Connected Successfully");
    app.listen(process.env.PORT || 8080, () => {
      console.log("Server Started Successfully");
    });
  } catch (err) {
    console.log(err);
  }
};

// Starting Server

app.get("/", (req, res) => {
  res.send(
    `<h1> Your book shelf is ready. Please visit <a href="/bookshelf">BookShelf</a> to continue :) </h1>`,
  );
});

app.use("/bookshelf", bookShelfRouter);

app.use("/bookshelf/:id/reviews", reviewRouter);

app.use("/", userRouter);

app.use((req, res, next) => {
  return next(createError(404, "Page Not Found"));
});

app.use((err, req, res, next) => {
  const { status = 404, message = "Error Please Try Again Later" } = err;
  res.status(status).json({ msg: message });
});

main();
